//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to news.
        /// </summary>
        public static string CannotConvertNullToNews {
            get {
                return ResourceManager.GetString("CannotConvertNullToNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert null to streetcodeCoordinate.
        /// </summary>
        public static string CannotConvertNullToStreetcodeCoordinate {
            get {
                return ResourceManager.GetString("CannotConvertNullToStreetcodeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create DTOs for related words!.
        /// </summary>
        public static string CannotCreateRelatedWordDtos {
            get {
                return ResourceManager.GetString("CannotCreateRelatedWordDtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create new related word for a term!.
        /// </summary>
        public static string CannotCreateRelatedWordForTerm {
            get {
                return ResourceManager.GetString("CannotCreateRelatedWordForTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any arts.
        /// </summary>
        public static string CannotFindAnyArts {
            get {
                return ResourceManager.GetString("CannotFindAnyArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any audios.
        /// </summary>
        public static string CannotFindAnyAudios {
            get {
                return ResourceManager.GetString("CannotFindAnyAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any team links.
        /// </summary>
        public static string CannotFindAnyTeamLinks {
            get {
                return ResourceManager.GetString("CannotFindAnyTeamLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any text.
        /// </summary>
        public static string CannotFindAnyText {
            get {
                return ResourceManager.GetString("CannotFindAnyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an art with corresponding id: {0}.
        /// </summary>
        public static string CannotFindArtById {
            get {
                return ResourceManager.GetString("CannotFindArtById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any art with corresponding streetcode id: {0}.
        /// </summary>
        public static string CannotFindArtByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindArtByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with corresponding categoryId: {0}.
        /// </summary>
        public static string CannotFindAudioByCategoryId {
            get {
                return ResourceManager.GetString("CannotFindAudioByCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with corresponding id: {0}.
        /// </summary>
        public static string CannotFindAudioById {
            get {
                return ResourceManager.GetString("CannotFindAudioById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find an audio with the corresponding streetcode id: {0}.
        /// </summary>
        public static string CannotFindAudioByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindAudioByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a coordinate with corresponding categoryId: {0}.
        /// </summary>
        public static string CannotFindCoordinateByCategoryId {
            get {
                return ResourceManager.GetString("CannotFindCoordinateByCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find one or more historical contexts.
        /// </summary>
        public static string CannotFindOneOrMoreHistoricalContexts {
            get {
                return ResourceManager.GetString("CannotFindOneOrMoreHistoricalContexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partner with corresponding id: {0}.
        /// </summary>
        public static string CannotFindPartnerById {
            get {
                return ResourceManager.GetString("CannotFindPartnerById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a partners by a streetcode id: {0}.
        /// </summary>
        public static string CannotFindPartnersByStreetcode {
            get {
                return ResourceManager.GetString("CannotFindPartnersByStreetcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any partners with corresponding streetcode id: {0}.
        /// </summary>
        public static string CannotFindPartnersByStreetcodeId {
            get {
                return ResourceManager.GetString("CannotFindPartnersByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a related term: {0}.
        /// </summary>
        public static string CannotFindRelatedTerm {
            get {
                return ResourceManager.GetString("CannotFindRelatedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any text with corresponding id: {0}.
        /// </summary>
        public static string CannotFindTextById {
            get {
                return ResourceManager.GetString("CannotFindTextById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get words by term id.
        /// </summary>
        public static string CannotGetWordsByTermId {
            get {
                return ResourceManager.GetString("CannotGetWordsByTermId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot map entity!.
        /// </summary>
        public static string CannotMapEntity {
            get {
                return ResourceManager.GetString("CannotMapEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save historical context to database.
        /// </summary>
        public static string CannotSaveHistoricalContextToDatabase {
            get {
                return ResourceManager.GetString("CannotSaveHistoricalContextToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save changes in the database after related word creation!.
        /// </summary>
        public static string CannotSaveRelatedWordChanges {
            get {
                return ResourceManager.GetString("CannotSaveRelatedWordChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save timeline item to database.
        /// </summary>
        public static string CannotSaveTimelineItem {
            get {
                return ResourceManager.GetString("CannotSaveTimelineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Connection is missing.
        /// </summary>
        public static string DefaultConnectionIsMissing {
            get {
                return ResourceManager.GetString("DefaultConnectionIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Configuration is missing.
        /// </summary>
        public static string EmailConfigurationIsMissing {
            get {
                return ResourceManager.GetString("EmailConfigurationIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create an audio.
        /// </summary>
        public static string FailedToCreateAudio {
            get {
                return ResourceManager.GetString("FailedToCreateAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a news.
        /// </summary>
        public static string FailedToCreateNews {
            get {
                return ResourceManager.GetString("FailedToCreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a streetcodeCoordinate.
        /// </summary>
        public static string FailedToCreateStreetcodeCoordinate {
            get {
                return ResourceManager.GetString("FailedToCreateStreetcodeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete an audio.
        /// </summary>
        public static string FailedToDeleteAnAudio {
            get {
                return ResourceManager.GetString("FailedToDeleteAnAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a coordinate.
        /// </summary>
        public static string FailedToDeleteCoordinate {
            get {
                return ResourceManager.GetString("FailedToDeleteCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete historical context with id {0}.
        /// </summary>
        public static string FailedToDeleteHistoricalContextWithId {
            get {
                return ResourceManager.GetString("FailedToDeleteHistoricalContextWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete news.
        /// </summary>
        public static string FailedToDeleteNews {
            get {
                return ResourceManager.GetString("FailedToDeleteNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete a related term.
        /// </summary>
        public static string FailedToDeleteRelatedTerm {
            get {
                return ResourceManager.GetString("FailedToDeleteRelatedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete timeline item with id {0}.
        /// </summary>
        public static string FailedToDeleteTimelineItemWithId {
            get {
                return ResourceManager.GetString("FailedToDeleteTimelineItemWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update historical context with id {0}.
        /// </summary>
        public static string FailedToUpdateHistoricalContextWithId {
            get {
                return ResourceManager.GetString("FailedToUpdateHistoricalContextWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update news.
        /// </summary>
        public static string FailedToUpdateNews {
            get {
                return ResourceManager.GetString("FailedToUpdateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update a streetcodeCoordinate.
        /// </summary>
        public static string FailedToUpdateStreetcodeCoordinate {
            get {
                return ResourceManager.GetString("FailedToUpdateStreetcodeCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update timeline item with id {0}.
        /// </summary>
        public static string FailedToUpdateTimelineItemWithId {
            get {
                return ResourceManager.GetString("FailedToUpdateTimelineItemWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical context with id {0} not found.
        /// </summary>
        public static string HistoricalContextWithIdNotFound {
            get {
                return ResourceManager.GetString("HistoricalContextWithIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news found by entered Id - {0}.
        /// </summary>
        public static string NoNewsFoundById {
            get {
                return ResourceManager.GetString("NoNewsFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No news by entered Url - {0}.
        /// </summary>
        public static string NoNewsFoundByUrl {
            get {
                return ResourceManager.GetString("NoNewsFoundByUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No partner with such id.
        /// </summary>
        public static string NoPartnerWithSuchId {
            get {
                return ResourceManager.GetString("NoPartnerWithSuchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово з цим визначенням уже існує.
        /// </summary>
        public static string RelatedWordAlreadyExists {
            get {
                return ResourceManager.GetString("RelatedWordAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no news in the database.
        /// </summary>
        public static string ThereAreNoNewsInDatabase {
            get {
                return ResourceManager.GetString("ThereAreNoNewsInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline item with id {0} not found.
        /// </summary>
        public static string TimelineItemWithIdNotFound {
            get {
                return ResourceManager.GetString("TimelineItemWithIdNotFound", resourceCulture);
            }
        }
    }
}
